# Copyright (C) 2017 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the MIT license

language: cpp
dist: trusty

env:
  global:
    - CFLAGS='-g -pipe'
  matrix:
    - MODE=address
    - MODE=lib-coverage

addons:
  apt:
    packages:
      - docbook2x

install:
  - wget -O expat/tests/xmlts.zip https://www.w3.org/XML/Test/xmlts20080827.zip

script:
  - cd expat
  - ./buildconf.sh
  - ./qa.sh ${MODE}
